spawn_platforms(
    platform_plan,
    world_offset,
    WIDTH,
    spawn_distance,
    TILE_SIZE,
    Platform,
    all_sprites,
    world_sprites,
    platforms,
)
spawn_coins(
    coin_plan,
    world_offset,
    WIDTH,
    spawn_distance,
    Coin,
    all_sprites,
    world_sprites,
    coins
)
spawn_enemies(
    enemy_plan,
    world_offset,
    WIDTH,
    enemy_spawn_distance,
    gravity,
    Enemy,
    platforms,
    all_sprites,
    world_sprites,
    enemies,
)
